# Generated by Django 3.0.6 on 2020-05-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0002_auto_20200530_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
